name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        env:
          fetch-depth: 0

      - name: Push to coveralls.io
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          cargo install cargo-tarpaulin
          cargo tarpaulin --all-targets --all-features --ciserver github-ci --coveralls $COVERALLS_REPO_TOKEN --engine llvm

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --verbose --all-targets

      - name: Run tests (Standard)
        run: cargo test --verbose --all-targets

      - name: Run tests (Encoding Only)
        run: cargo test --verbose --all-targets --no-default-features --features=encoding

      - name: Run tests (No Features)
        run: cargo test --verbose --all-targets --no-default-features

      - name: Run tests (All Features)
        run: cargo test --verbose --all-targets --all-features

      - name: Clippy (All Features)
        run: |
          rustup component add clippy
          cargo clippy --all-targets --all-features
