name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --verbose

      - name: Run tests (Standard)
        run: cargo test --verbose

      - name: Run tests (Encoding Only)
        run: cargo test --verbose --no-default-features --features=encoding

      - name: Run tests (No Features)
        run: cargo test --verbose --no-default-features

      - name: Run tests (All Features)
        run: cargo test --verbose --all-features
